/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/Volcano.glb --transform 
Files: src/assets/Volcano.glb [334.82KB] > /workspaces/threejs-playground/Volcano-transformed.glb [57.31KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import volcanoUrl from '../assets/Volcano-transformed.glb'
import * as THREE from 'three'

export function Volcano(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(volcanoUrl)
  return (
    <group {...props} dispose={null}>
      <group scale={8.639}>
        <mesh geometry={(nodes.Plane as THREE.Mesh).geometry} material={materials['Material.001']} />
        <mesh geometry={(nodes.Plane_1 as THREE.Mesh).geometry} material={materials['Material.003']} />
        <mesh geometry={(nodes.Plane_2 as THREE.Mesh).geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload(volcanoUrl)
