/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 volcano.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/volcano.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={8.639}>
        <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/volcano.glb')
